"""Existence guards, so a migration can run over a schema that already has it.

Migrations are re-run more often than the "each revision executes exactly once"
contract suggests: a restored backup, a DB whose ``alembic_version_motoro`` row
was lost or hand-edited, or a verification run that left the schema behind
without the stamp. Alembic's own ``if_not_exists=``/``if_exists=`` kwargs cover
creating tables, indexes and columns (and ``op.drop_*`` for tables, indexes and
constraints), and every call site in ``versions/`` passes them. What's left is
what this module fills in: ``CREATE TYPE``, ``DROP COLUMN`` and
``ADD CONSTRAINT``, none of which Alembic exposes a flag for.

``op.alter_column`` needs no guard: every use here declares a target state
(``nullable=``, ``type_=``, ``server_default=``), and asking Postgres for the
state a column is already in is a successful no-op.

What this deliberately does NOT do is reconcile a *differing* schema. A table
that already exists with the wrong columns is accepted silently -- guarding
existence buys "re-running is safe", not "the schema is correct". The stamp is
still the source of truth; this only stops a drifted one from wedging a deploy.

Historical migrations import from here, so these signatures are permanent:
changing one rewrites the meaning of a revision that already ran elsewhere.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def enum_type(name: str, *labels: str) -> postgresql.ENUM:
    """Create a Postgres enum if absent, and return a type that won't re-create it.

    Called inline where the column type goes::

        sa.Column("transport", enum_type("mcp_transport", "stdio", "http"), nullable=False)

    The ``CREATE TYPE`` runs as a side effect of building that argument, which
    is *before* the enclosing ``op.create_table`` executes -- the ordering
    ``CREATE TABLE`` needs, and the ordering an offline ``--sql`` run emits too.
    ``create_type=False`` on the returned type is what stops SQLAlchemy emitting
    its own unguarded ``CREATE TYPE`` a second time.

    A ``DO`` block rather than a catalog lookup: ``CREATE TYPE`` and a preceding
    ``SELECT FROM pg_type`` are two statements another migration can interleave
    with, whereas swallowing ``duplicate_object`` cannot lose that race.
    """
    quoted = ", ".join("'" + label.replace("'", "''") + "'" for label in labels)
    op.execute(
        sa.text(
            f"""
            DO $$ BEGIN
                CREATE TYPE {name} AS ENUM ({quoted});
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
            """
        )
    )
    return postgresql.ENUM(*labels, name=name, create_type=False)


def drop_column(table: str, column: str) -> None:
    """``op.drop_column`` with the ``IF EXISTS`` that Alembic doesn't expose.

    ``ALTER TABLE ... DROP COLUMN IF EXISTS`` is plain Postgres, so this is the
    same statement Alembic would emit with the clause appended -- not a
    catalog check, and nothing to race. Identifiers are quoted rather than
    interpolated bare so a column named after a keyword still resolves; every
    call site passes a literal from an autogenerated migration.
    """
    op.execute(sa.text(f'ALTER TABLE "{table}" DROP COLUMN IF EXISTS "{column}"'))


def create_foreign_key(
    name: str,
    source_table: str,
    referent_table: str,
    local_cols: Sequence[str],
    remote_cols: Sequence[str],
    *,
    ondelete: str | None = None,
) -> None:
    """``op.create_foreign_key`` that tolerates the constraint already being there.

    ``ADD CONSTRAINT`` has no ``IF NOT EXISTS`` in Postgres, so this takes the
    same ``DO``/``duplicate_object`` shape as :func:`enum_type`. Only the
    argument subset the migrations here actually use is accepted -- adding a
    parameter later is safe, but a caller must never silently lose one.
    """
    local = ", ".join(f'"{col}"' for col in local_cols)
    remote = ", ".join(f'"{col}"' for col in remote_cols)
    clause = f" ON DELETE {ondelete}" if ondelete else ""
    op.execute(
        sa.text(
            f"""
            DO $$ BEGIN
                ALTER TABLE "{source_table}" ADD CONSTRAINT "{name}"
                    FOREIGN KEY ({local}) REFERENCES "{referent_table}" ({remote}){clause};
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;
            """
        )
    )
