"""baseline: core schema

Revision ID: c58058956d24
Revises: 
Create Date: 2026-07-30 13:02:36.491980
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = 'c58058956d24'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_contract', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('budget_limit_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_run_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('auto_eval_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('auto_eval_model', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_index('uq_agents_name_active', 'agents', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('architectural_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('execution', 'safety', 'coordination', 'knowledge', 'quality', 'routing', 'resolution', name='pattern_category', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phase', sa.Enum('basic', 'dynamic', 'introspective', 'self_correcting', 'multi_agent', 'advanced_multi_agent', name='pattern_phase', create_constraint=True), nullable=False),
    sa.Column('configuration_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_multi_agent', sa.Boolean(), nullable=False),
    sa.Column('dependencies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architectural_patterns_category'), 'architectural_patterns', ['category'], unique=False)
    op.create_index(op.f('ix_architectural_patterns_is_implemented'), 'architectural_patterns', ['is_implemented'], unique=False)
    op.create_index(op.f('ix_architectural_patterns_phase'), 'architectural_patterns', ['phase'], unique=False)
    op.create_index(op.f('ix_architectural_patterns_slug'), 'architectural_patterns', ['slug'], unique=True)
    op.create_table('llm_pricing_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('input_cost_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_cost_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'paused', 'awaiting_human', name='run_status', create_constraint=True), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('state_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pattern_overrides', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config_overrides', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_agent_id', 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_owner_id'), 'agent_runs', ['owner_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Enum('sense', 'reason', 'plan', 'act', 'hitl', name='step_phase', create_constraint=True), nullable=False),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_call', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_steps_run_id', 'run_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_steps_run_id', table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_owner_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('llm_pricing_overrides')
    op.drop_index(op.f('ix_architectural_patterns_slug'), table_name='architectural_patterns')
    op.drop_index(op.f('ix_architectural_patterns_phase'), table_name='architectural_patterns')
    op.drop_index(op.f('ix_architectural_patterns_is_implemented'), table_name='architectural_patterns')
    op.drop_index(op.f('ix_architectural_patterns_category'), table_name='architectural_patterns')
    op.drop_table('architectural_patterns')
    op.drop_index('uq_agents_name_active', table_name='agents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###

    # Hand-added: autogenerate emits CREATE TYPE for a native enum but never the
    # matching DROP TYPE, so a downgrade leaves the types behind and the next
    # upgrade fails with `type "pattern_category" already exists`. Dropping the
    # tables does not cascade to the types — they are schema-level objects.
    for enum_name in ("step_phase", "run_status", "pattern_phase", "pattern_category"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
